### ISSUE TITLE
Cannot register on nodelua.org

### ISSUE THREAD

**Issue by SmartSouth** [liangchen-harold/nodelua#9]
I've tried registering with two email addresses but it says they're registered. Tried 'forgot password', didn't work. Needless to say, no Web IDE either.

**Comment by davewesson** [comment]
I just had the same problem on the site. 
Looking at the activity, nothing has happened for a year. 
Unfortunatly, I think this project is no longer active.

**Comment by liangchen-harold** [comment]
Sorry for that terrible bug which introduced at the last December!

I've fixed it today, please try again ;) For the case that you've registered and login with "wrong password" tips now, please use the "Forgot password" button~~
